'use strict';
const menu=document.querySelector('.menu-button'),nav=document.getElementById('mobile-nav');
function closeMenu(){nav.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','打开导航');}
menu.addEventListener('click',()=>{const open=nav.hidden;nav.hidden=!open;menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'关闭导航':'打开导航');});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
const valid=['all','cup','plate','vase'],params=new URLSearchParams(location.search);
const feedbackQuery=params.get('feedback')==='off'?'&feedback=off':'';
let category=valid.includes(params.get('category'))?params.get('category'):'all';
function filter(){document.querySelectorAll('[data-category]').forEach(c=>{c.hidden=category!=='all'&&c.dataset.category!==category;c.querySelector('a').href=`product-${c.dataset.category}.html?from=${category}${feedbackQuery}`;});document.querySelectorAll('[data-filter]').forEach(a=>a.setAttribute('aria-current',String(a.dataset.filter===category)));const count=document.getElementById('result-count');if(count)count.textContent=`${document.querySelectorAll('[data-category]:not([hidden])').length} 件器物`;}
document.querySelectorAll('[data-filter]').forEach(a=>a.addEventListener('click',e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();category=a.dataset.filter;history.pushState(null,'',a.href);filter();}));
window.addEventListener('popstate',()=>{const key=new URLSearchParams(location.search).get('category');category=valid.includes(key)?key:'all';filter();});filter();
const back=document.getElementById('back-catalog');if(back&&valid.includes(params.get('from'))){const key=params.get('from');back.href=`products.html?category=${key}${feedbackQuery}`;back.textContent=key==='all'?'← 返回全部器物':'← 返回原分类';}
document.querySelectorAll('.product-photo img').forEach(i=>{const fallback=()=>{const text=document.createElement('p');text.className='image-fallback';text.textContent='图片暂缺，器物资料仍可阅读';i.replaceWith(text);};if(i.complete&&!i.naturalWidth)fallback();else i.addEventListener('error',fallback,{once:true});});
const triggers=[...document.querySelectorAll('[data-quick]')];
if(triggers.length){
  triggers.forEach(b=>b.hidden=false);
  const dialog=document.createElement('dialog');dialog.setAttribute('aria-labelledby','quick-title');dialog.className='clg glass-dialog';dialog.dataset.glass='strong';dialog.innerHTML='<button class="dialog-close" aria-label="关闭快速查看"><img class="icon" src="x.svg" alt=""></button><div class="detail-layout clg__content"><div id="detail-image"></div><div class="detail-copy"><h2 id="quick-title"></h2><dl class="spec-list"><div><dt id="quick-spec"></dt><dd id="quick-size"></dd></div><div><dt>展示价格</dt><dd id="quick-price"></dd></div></dl><p>规格和价格均为演示数据，暂不销售。完整详情包含设计观察、场景与未核实的信息。</p><a class="text-link dialog-full" id="quick-link">阅读完整器物详情 →</a></div></div>';document.body.append(dialog);
  let dataPromise;triggers.forEach(b=>b.addEventListener('click',async e=>{dataPromise??=fetch('products.json').then(r=>{if(!r.ok)throw Error('data');return r.json();});try{const data=await dataPromise;const p=data.find(p=>p.id===b.dataset.quick);if(!p)return;dialog.querySelector('#quick-title').textContent=p.name;dialog.querySelector('#quick-spec').textContent=p.spec;dialog.querySelector('#quick-size').textContent=p.size;dialog.querySelector('#quick-price').textContent=`¥${p.price}`;const img=document.createElement('img');img.src=p.image;img.alt=p.name+'概念摄影';img.width=1254;img.height=1254;dialog.querySelector('#detail-image').replaceChildren(img);dialog.querySelector('#quick-link').href=`product-${p.id}.html?from=${category}${feedbackQuery}`;dialog.classList.toggle('motion-instant',e.detail===0);if(!dialog.open){b.focus();dialog.showModal();document.body.classList.add('modal-open');}}catch{location.href=b.closest('article').querySelector('a').href;}}));
  dialog.querySelector('.dialog-close').addEventListener('click',e=>{dialog.classList.toggle('motion-instant',e.detail===0);dialog.close();});dialog.addEventListener('cancel',()=>dialog.classList.add('motion-instant'));dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
}
